PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS meta (chave TEXT PRIMARY KEY, valor TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS contextos_financeiros (id INTEGER PRIMARY KEY, nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contas (id INTEGER PRIMARY KEY, contexto_id INTEGER NOT NULL REFERENCES contextos_financeiros(id), nome TEXT NOT NULL, tipo TEXT NOT NULL CHECK (tipo IN ('bancaria','cartao','investimento')), saldo_inicial_centavos INTEGER NOT NULL DEFAULT 0, ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categorias (id INTEGER PRIMARY KEY, contexto_id INTEGER NOT NULL REFERENCES contextos_financeiros(id), nome TEXT NOT NULL, natureza TEXT NOT NULL CHECK (natureza IN ('receita','despesa','ambas')), ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(contexto_id, nome));
CREATE TABLE IF NOT EXISTS lancamentos (id INTEGER PRIMARY KEY, contexto_id INTEGER NOT NULL REFERENCES contextos_financeiros(id), conta_id INTEGER NOT NULL REFERENCES contas(id), categoria_id INTEGER REFERENCES categorias(id), natureza TEXT NOT NULL CHECK (natureza IN ('receita','despesa')), valor_centavos INTEGER NOT NULL CHECK (valor_centavos > 0), data_competencia TEXT NOT NULL CHECK (data_competencia GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'), descricao TEXT NOT NULL, observacoes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK (status IN ('aberto','conciliado','estornado')), criado_em TEXT NOT NULL, atualizado_em TEXT);
CREATE TABLE IF NOT EXISTS auditoria (id INTEGER PRIMARY KEY, entidade TEXT NOT NULL, entidade_id INTEGER NOT NULL, acao TEXT NOT NULL, dados_json TEXT NOT NULL, criado_em TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS configuracoes (chave TEXT PRIMARY KEY, valor TEXT NOT NULL, tipo TEXT NOT NULL CHECK (tipo IN ('texto','numero','cor','booleano','arquivo')) DEFAULT 'texto', atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_lancamentos_contexto_data ON lancamentos(contexto_id, data_competencia);
